/** Feature-flag key that backs the platform-wide kill switch. */
export const KILL_SWITCH_FLAG_KEY = 'platform_kill_switch';

/** Audit action identifiers (kept in sync with the mockup's audit log). */
export const AuditAction = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  TX_RETRY: 'TX_RETRY',
  TX_REFRESH: 'TX_REFRESH',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_RESTORE: 'USER_RESTORE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_STATE_UPDATE: 'USER_STATE_UPDATE',
  KYC_APPROVE: 'KYC_APPROVE',
  USER_FREEZE: 'USER_FREEZE',
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  FLAG_TOGGLE: 'FLAG_TOGGLE',
  KILL_SWITCH_ON: 'KILL_SWITCH_ON',
  KILL_SWITCH_OFF: 'KILL_SWITCH_OFF',
  DATA_TABLE_VIEW: 'DATA_TABLE_VIEW',
  PAYMENT_LINK_CANCEL: 'PAYMENT_LINK_CANCEL',
  PAYMENT_LINK_EXTEND: 'PAYMENT_LINK_EXTEND',
  PAYMENT_LINK_CREATE: 'PAYMENT_LINK_CREATE',
  COMPLIANCE_UPDATE: 'COMPLIANCE_UPDATE',
  DISPUTE_UPDATE: 'DISPUTE_UPDATE',
  SUPPORT_REPLY: 'SUPPORT_REPLY',
  SUPPORT_THREAD_UPDATE: 'SUPPORT_THREAD_UPDATE',
  WEBHOOK_VIEW: 'WEBHOOK_VIEW',
  ADMIN_USER_CREATE: 'ADMIN_USER_CREATE',
  ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
  ADMIN_USER_DEACTIVATE: 'ADMIN_USER_DEACTIVATE',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
